### ISSUE TITLE
npm v5+ installation error

### ISSUE THREAD

**Issue by voldemarpro** [xenohunter/waves-api#24]
Found when installing
1) npm version 5+ requires package.json to be in the root (home) directory
2) npm refuses installation of package with name "waves-api" under a package also called "waves-api"
(self-dependency err) So, one should change name of the package in json file to any distinct one, and it will work.

**Comment by xenohunter** [comment]
Hello! What you describe sounds weird. Do you run `npm install` on your root directory? It shouldn't require any of that from you. The approximate sequence of actions is as follows:
```
mkdir some-project
cd some-project
git clone REPO_URL ./
npm i
```
That won't require _package.json_ file in the root directory.

**Comment by voldemarpro** [comment]
No, the command was (as specified at [https://www.npmjs.com/package/waves-api](url))
`npm install waves-api --save`
