### ISSUE TITLE
Types locate in 'raw/src/WavesAPI.d.ts', not in 'raw/WavesAPI.d.ts'

### ISSUE THREAD

**Issue by Fame513** [xenohunter/waves-api#27]
In package.json: "types": "raw/WavesAPI.d.ts", but real it located in 'raw/src/WavesAPI.d.ts'
Version: "0.21.5"

**Comment by xenohunter** [comment]
Hello! Thanks for reporting! I will fix that soon.

**Comment by xenohunter** [comment]
Fixed in 842abf3b14098eb1e8af2a6888815a6be9cdc012.
